language: python

matrix:
  - os: linux
    dist: xenial
    services: xvfb
  - os: osx
    osx_image: xcode11.2
    language: shell  # 'language: python' is an error on Travis CI macOS


python: "3.7"

install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - type python; whereis python; which python
  - pip3 install virtualenv --upgrade
  - python3 -m virtualenv guizero-env
  - source guizero-env/bin/activate
  - pip3 install mkdocs wheel twine virtualenv pytest pillow --upgrade
  - python setup.py develop

script:
  - cd tests
  - pytest -v

