language: python

matrix:
  - os: linux
    dist: xenial
  - os: osx
    osx_image: xcode11.2
    language: shell       # 'language: python' is an error on Travis CI macOS

services:
  - xvfb

python: "3.7"

install:
  - python -m pip install virtualenv --upgrade
  - python -m virtualenv guizero-env
  - source guizero-env/bin/activate
  - pip install mkdocs wheel twine virtualenv pytest pillow --upgrade
  - python setup.py develop

script:
  - cd tests
  - pytest -v

